# Generated by Django 6.0.3 on 2026-04-07 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('time_stamp', models.CharField(max_length=32)),
                ('miner', models.CharField(max_length=32)),
                ('gase_used', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=32, unique=True)),
                ('from_address', models.CharField(max_length=32)),
                ('to_address', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=32)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.block')),
            ],
        ),
    ]
