# Generated by Django 6.0.3 on 2026-04-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='gase_used',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='miner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='time_stamp',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hash',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
